# Generated by Django 2.2.1 on 2019-06-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='主机名称')),
                ('ip', models.CharField(max_length=125, verbose_name='主机ip')),
                ('username', models.CharField(max_length=125, verbose_name='用户名')),
                ('password', models.CharField(max_length=125, verbose_name='密码')),
                ('port', models.IntegerField(max_length=22, verbose_name='端口')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
    ]
